language: python
python:
- '3.6'
notifications:
  email: false

install:
- travis_retry pip install .
# coverage packages
- travis_retry pip install flake8
- travis_retry pip install codecov coverage
- pip freeze
script:
- travis_wait 30 coverage run --source=ggf setup.py test
- coverage report -m
- codecov
- flake8 ggf
- flake8 examples
- flake8 tests
