language: python
python:
- '3.6'
notifications:
  email: false
env:
  matrix:
  - TEST="PYTEST"
#  - TEST="FLAKE8"
install:
- travis_retry pip install .
# coverage packages
- travis_retry pip install flake8
- travis_retry pip install codecov coverage
- pip freeze
script:
- set -ev
- if [ "${TEST}" == "PYTEST" ]; then
       travis_wait 30 coverage run --source=ggf setup.py test;
       coverage report -m;
       codecov;
  else
       flake8 drymass;
       flake8 examples;
       flake8 tests;
  fi;
